#!/usr/bin/python

"""Amulet tests on a basic odl controller deployment on trusty-juno."""

from basic_deployment import ODLControllerBasicDeployment

if __name__ == '__main__':
    deployment = ODLControllerBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-juno',
                                           source='cloud:trusty-updates/juno')
    deployment.run_tests()
