#!/usr/bin/python

"""Amulet tests on a basic odl controller deployment on trusty-liberty."""

from basic_deployment import ODLControllerBasicDeployment

if __name__ == '__main__':
    deployment = ODLControllerBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-liberty',
                                           source='cloud:trusty-updates/liberty')
    deployment.run_tests()
