#!/usr/bin/python

"""Amulet tests on a basic odl controller deployment on trusty-mitaka."""

from basic_deployment import ODLControllerBasicDeployment

if __name__ == '__main__':
    deployment = ODLControllerBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-mitaka',
                                           source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
