#!/usr/bin/python

"""Amulet tests on a basic odl controller deployment on xenial-mitaka."""

from basic_deployment import ODLControllerBasicDeployment

if __name__ == '__main__':
    deployment = ODLControllerBasicDeployment(series='xenial')
    deployment.run_tests()
